/**
 * This class is generated by jOOQ
 */
package models.garaDB.tables.daos;


import models.garaDB.tables.City;
import models.garaDB.tables.records.CityRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CityDao extends DAOImpl<CityRecord, models.garaDB.tables.pojos.City, Integer> {

    /**
     * Create a new CityDao without any configuration
     */
    public CityDao() {
        super(City.CITY, models.garaDB.tables.pojos.City.class);
    }

    /**
     * Create a new CityDao with an attached configuration
     */
    public CityDao(Configuration configuration) {
        super(City.CITY, models.garaDB.tables.pojos.City.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(models.garaDB.tables.pojos.City object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.City> fetchById(Integer... values) {
        return fetch(City.CITY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public models.garaDB.tables.pojos.City fetchOneById(Integer value) {
        return fetchOne(City.CITY.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.City> fetchByName(String... values) {
        return fetch(City.CITY.NAME, values);
    }

    /**
     * Fetch records that have <code>countryID IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.City> fetchByCountryid(Integer... values) {
        return fetch(City.CITY.COUNTRYID, values);
    }

    /**
     * Fetch records that have <code>pic IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.City> fetchByPic(String... values) {
        return fetch(City.CITY.PIC, values);
    }

    /**
     * Fetch records that have <code>longitude IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.City> fetchByLongitude(Double... values) {
        return fetch(City.CITY.LONGITUDE, values);
    }

    /**
     * Fetch records that have <code>latitude IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.City> fetchByLatitude(Double... values) {
        return fetch(City.CITY.LATITUDE, values);
    }
}
