/**
 * This class is generated by jOOQ
 */
package models.garaDB.tables.daos;


import models.garaDB.tables.Driver;
import models.garaDB.tables.records.DriverRecord;

import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DriverDao extends DAOImpl<DriverRecord, models.garaDB.tables.pojos.Driver, Integer> {

    /**
     * Create a new DriverDao without any configuration
     */
    public DriverDao() {
        super(Driver.DRIVER, models.garaDB.tables.pojos.Driver.class);
    }

    /**
     * Create a new DriverDao with an attached configuration
     */
    public DriverDao(Configuration configuration) {
        super(Driver.DRIVER, models.garaDB.tables.pojos.Driver.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(models.garaDB.tables.pojos.Driver object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Driver> fetchById(Integer... values) {
        return fetch(Driver.DRIVER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public models.garaDB.tables.pojos.Driver fetchOneById(Integer value) {
        return fetchOne(Driver.DRIVER.ID, value);
    }

    /**
     * Fetch records that have <code>memberID IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Driver> fetchByMemberid(Integer... values) {
        return fetch(Driver.DRIVER.MEMBERID, values);
    }

    /**
     * Fetch records that have <code>licenseNumber IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Driver> fetchByLicensenumber(String... values) {
        return fetch(Driver.DRIVER.LICENSENUMBER, values);
    }

    /**
     * Fetch records that have <code>licensePic IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Driver> fetchByLicensepic(String... values) {
        return fetch(Driver.DRIVER.LICENSEPIC, values);
    }

    /**
     * Fetch records that have <code>identyCardPic IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Driver> fetchByIdentycardpic(String... values) {
        return fetch(Driver.DRIVER.IDENTYCARDPIC, values);
    }

    /**
     * Fetch records that have <code>licenseExpireDate IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Driver> fetchByLicenseexpiredate(Date... values) {
        return fetch(Driver.DRIVER.LICENSEEXPIREDATE, values);
    }
}
