/**
 * This class is generated by jOOQ
 */
package models.garaDB.tables.daos;


import models.garaDB.tables.Membercard;
import models.garaDB.tables.records.MembercardRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MembercardDao extends DAOImpl<MembercardRecord, models.garaDB.tables.pojos.Membercard, Integer> {

    /**
     * Create a new MembercardDao without any configuration
     */
    public MembercardDao() {
        super(Membercard.MEMBERCARD, models.garaDB.tables.pojos.Membercard.class);
    }

    /**
     * Create a new MembercardDao with an attached configuration
     */
    public MembercardDao(Configuration configuration) {
        super(Membercard.MEMBERCARD, models.garaDB.tables.pojos.Membercard.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(models.garaDB.tables.pojos.Membercard object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Membercard> fetchById(Integer... values) {
        return fetch(Membercard.MEMBERCARD.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public models.garaDB.tables.pojos.Membercard fetchOneById(Integer value) {
        return fetchOne(Membercard.MEMBERCARD.ID, value);
    }

    /**
     * Fetch records that have <code>memberID IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Membercard> fetchByMemberid(Integer... values) {
        return fetch(Membercard.MEMBERCARD.MEMBERID, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Membercard> fetchByType(String... values) {
        return fetch(Membercard.MEMBERCARD.TYPE, values);
    }

    /**
     * Fetch records that have <code>number IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Membercard> fetchByNumber(String... values) {
        return fetch(Membercard.MEMBERCARD.NUMBER, values);
    }

    /**
     * Fetch records that have <code>expireDate IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Membercard> fetchByExpiredate(String... values) {
        return fetch(Membercard.MEMBERCARD.EXPIREDATE, values);
    }

    /**
     * Fetch records that have <code>secrit IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Membercard> fetchBySecrit(String... values) {
        return fetch(Membercard.MEMBERCARD.SECRIT, values);
    }

    /**
     * Fetch records that have <code>TIMESTAMP IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Membercard> fetchByTimestamp(Timestamp... values) {
        return fetch(Membercard.MEMBERCARD.TIMESTAMP, values);
    }
}
