/**
 * This class is generated by jOOQ
 */
package models.garaDB.tables.daos;


import models.garaDB.tables.Membergroup;
import models.garaDB.tables.records.MembergroupRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MembergroupDao extends DAOImpl<MembergroupRecord, models.garaDB.tables.pojos.Membergroup, Integer> {

    /**
     * Create a new MembergroupDao without any configuration
     */
    public MembergroupDao() {
        super(Membergroup.MEMBERGROUP, models.garaDB.tables.pojos.Membergroup.class);
    }

    /**
     * Create a new MembergroupDao with an attached configuration
     */
    public MembergroupDao(Configuration configuration) {
        super(Membergroup.MEMBERGROUP, models.garaDB.tables.pojos.Membergroup.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(models.garaDB.tables.pojos.Membergroup object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Membergroup> fetchById(Integer... values) {
        return fetch(Membergroup.MEMBERGROUP.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public models.garaDB.tables.pojos.Membergroup fetchOneById(Integer value) {
        return fetchOne(Membergroup.MEMBERGROUP.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Membergroup> fetchByName(String... values) {
        return fetch(Membergroup.MEMBERGROUP.NAME, values);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Membergroup> fetchByDescription(String... values) {
        return fetch(Membergroup.MEMBERGROUP.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>permissions IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Membergroup> fetchByPermissions(String... values) {
        return fetch(Membergroup.MEMBERGROUP.PERMISSIONS, values);
    }
}
