/**
 * This class is generated by jOOQ
 */
package models.garaDB.tables.daos;


import models.garaDB.tables.Ride;
import models.garaDB.tables.records.RideRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RideDao extends DAOImpl<RideRecord, models.garaDB.tables.pojos.Ride, Integer> {

    /**
     * Create a new RideDao without any configuration
     */
    public RideDao() {
        super(Ride.RIDE, models.garaDB.tables.pojos.Ride.class);
    }

    /**
     * Create a new RideDao with an attached configuration
     */
    public RideDao(Configuration configuration) {
        super(Ride.RIDE, models.garaDB.tables.pojos.Ride.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(models.garaDB.tables.pojos.Ride object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Ride> fetchById(Integer... values) {
        return fetch(Ride.RIDE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public models.garaDB.tables.pojos.Ride fetchOneById(Integer value) {
        return fetchOne(Ride.RIDE.ID, value);
    }

    /**
     * Fetch records that have <code>TIMESTAMP IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Ride> fetchByTimestamp(Timestamp... values) {
        return fetch(Ride.RIDE.TIMESTAMP, values);
    }

    /**
     * Fetch records that have <code>sourceLongitude IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Ride> fetchBySourcelongitude(Double... values) {
        return fetch(Ride.RIDE.SOURCELONGITUDE, values);
    }

    /**
     * Fetch records that have <code>sourceLatitude IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Ride> fetchBySourcelatitude(Double... values) {
        return fetch(Ride.RIDE.SOURCELATITUDE, values);
    }

    /**
     * Fetch records that have <code>destinationLongitude IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Ride> fetchByDestinationlongitude(Double... values) {
        return fetch(Ride.RIDE.DESTINATIONLONGITUDE, values);
    }

    /**
     * Fetch records that have <code>destinationLatitude IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Ride> fetchByDestinationlatitude(Double... values) {
        return fetch(Ride.RIDE.DESTINATIONLATITUDE, values);
    }

    /**
     * Fetch records that have <code>fare IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Ride> fetchByFare(Integer... values) {
        return fetch(Ride.RIDE.FARE, values);
    }

    /**
     * Fetch records that have <code>startTime IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Ride> fetchByStarttime(Timestamp... values) {
        return fetch(Ride.RIDE.STARTTIME, values);
    }

    /**
     * Fetch records that have <code>endTime IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Ride> fetchByEndtime(Timestamp... values) {
        return fetch(Ride.RIDE.ENDTIME, values);
    }

    /**
     * Fetch records that have <code>carID IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Ride> fetchByCarid(Integer... values) {
        return fetch(Ride.RIDE.CARID, values);
    }

    /**
     * Fetch records that have <code>accepted IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Ride> fetchByAccepted(Integer... values) {
        return fetch(Ride.RIDE.ACCEPTED, values);
    }

    /**
     * Fetch records that have <code>driverCheck IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Ride> fetchByDrivercheck(Integer... values) {
        return fetch(Ride.RIDE.DRIVERCHECK, values);
    }

    /**
     * Fetch records that have <code>passangerCheck IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Ride> fetchByPassangercheck(Integer... values) {
        return fetch(Ride.RIDE.PASSANGERCHECK, values);
    }

    /**
     * Fetch records that have <code>memberID IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Ride> fetchByMemberid(Integer... values) {
        return fetch(Ride.RIDE.MEMBERID, values);
    }
}
