/**
 * This class is generated by jOOQ
 */
package models.garaDB.tables.daos;


import models.garaDB.tables.Sitecontent;
import models.garaDB.tables.records.SitecontentRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SitecontentDao extends DAOImpl<SitecontentRecord, models.garaDB.tables.pojos.Sitecontent, Integer> {

    /**
     * Create a new SitecontentDao without any configuration
     */
    public SitecontentDao() {
        super(Sitecontent.SITECONTENT, models.garaDB.tables.pojos.Sitecontent.class);
    }

    /**
     * Create a new SitecontentDao with an attached configuration
     */
    public SitecontentDao(Configuration configuration) {
        super(Sitecontent.SITECONTENT, models.garaDB.tables.pojos.Sitecontent.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(models.garaDB.tables.pojos.Sitecontent object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Sitecontent> fetchById(Integer... values) {
        return fetch(Sitecontent.SITECONTENT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public models.garaDB.tables.pojos.Sitecontent fetchOneById(Integer value) {
        return fetchOne(Sitecontent.SITECONTENT.ID, value);
    }

    /**
     * Fetch records that have <code>TIMESTAMP IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Sitecontent> fetchByTimestamp(Timestamp... values) {
        return fetch(Sitecontent.SITECONTENT.TIMESTAMP, values);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Sitecontent> fetchByTitle(String... values) {
        return fetch(Sitecontent.SITECONTENT.TITLE, values);
    }

    /**
     * Fetch records that have <code>body IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Sitecontent> fetchByBody(String... values) {
        return fetch(Sitecontent.SITECONTENT.BODY, values);
    }

    /**
     * Fetch records that have <code>link IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Sitecontent> fetchByLink(String... values) {
        return fetch(Sitecontent.SITECONTENT.LINK, values);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Sitecontent> fetchByDescription(String... values) {
        return fetch(Sitecontent.SITECONTENT.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>keywords IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Sitecontent> fetchByKeywords(String... values) {
        return fetch(Sitecontent.SITECONTENT.KEYWORDS, values);
    }

    /**
     * Fetch records that have <code>pic IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Sitecontent> fetchByPic(String... values) {
        return fetch(Sitecontent.SITECONTENT.PIC, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.Sitecontent> fetchByName(String... values) {
        return fetch(Sitecontent.SITECONTENT.NAME, values);
    }
}
