/**
 * This class is generated by jOOQ
 */
package models.garaDB.tables.daos;


import models.garaDB.tables.University;
import models.garaDB.tables.records.UniversityRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UniversityDao extends DAOImpl<UniversityRecord, models.garaDB.tables.pojos.University, Integer> {

    /**
     * Create a new UniversityDao without any configuration
     */
    public UniversityDao() {
        super(University.UNIVERSITY, models.garaDB.tables.pojos.University.class);
    }

    /**
     * Create a new UniversityDao with an attached configuration
     */
    public UniversityDao(Configuration configuration) {
        super(University.UNIVERSITY, models.garaDB.tables.pojos.University.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(models.garaDB.tables.pojos.University object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.University> fetchById(Integer... values) {
        return fetch(University.UNIVERSITY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public models.garaDB.tables.pojos.University fetchOneById(Integer value) {
        return fetchOne(University.UNIVERSITY.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.University> fetchByName(String... values) {
        return fetch(University.UNIVERSITY.NAME, values);
    }

    /**
     * Fetch records that have <code>cityID IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.University> fetchByCityid(Integer... values) {
        return fetch(University.UNIVERSITY.CITYID, values);
    }

    /**
     * Fetch records that have <code>longitude IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.University> fetchByLongitude(Double... values) {
        return fetch(University.UNIVERSITY.LONGITUDE, values);
    }

    /**
     * Fetch records that have <code>latitude IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.University> fetchByLatitude(Double... values) {
        return fetch(University.UNIVERSITY.LATITUDE, values);
    }

    /**
     * Fetch records that have <code>pic IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.University> fetchByPic(String... values) {
        return fetch(University.UNIVERSITY.PIC, values);
    }

    /**
     * Fetch records that have <code>url IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.University> fetchByUrl(String... values) {
        return fetch(University.UNIVERSITY.URL, values);
    }

    /**
     * Fetch records that have <code>emailFormat IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.University> fetchByEmailformat(String... values) {
        return fetch(University.UNIVERSITY.EMAILFORMAT, values);
    }

    /**
     * Fetch records that have <code>pageName IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.University> fetchByPagename(String... values) {
        return fetch(University.UNIVERSITY.PAGENAME, values);
    }

    /**
     * Fetch records that have <code>pageContent IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.University> fetchByPagecontent(String... values) {
        return fetch(University.UNIVERSITY.PAGECONTENT, values);
    }

    /**
     * Fetch records that have <code>pageDescription IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.University> fetchByPagedescription(String... values) {
        return fetch(University.UNIVERSITY.PAGEDESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>pageKeywords IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.University> fetchByPagekeywords(String... values) {
        return fetch(University.UNIVERSITY.PAGEKEYWORDS, values);
    }

    /**
     * Fetch records that have <code>pageSubdomain IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.University> fetchByPagesubdomain(String... values) {
        return fetch(University.UNIVERSITY.PAGESUBDOMAIN, values);
    }

    /**
     * Fetch records that have <code>contactPersonEmail IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.University> fetchByContactpersonemail(String... values) {
        return fetch(University.UNIVERSITY.CONTACTPERSONEMAIL, values);
    }

    /**
     * Fetch records that have <code>contactPersonPassword IN (values)</code>
     */
    public List<models.garaDB.tables.pojos.University> fetchByContactpersonpassword(String... values) {
        return fetch(University.UNIVERSITY.CONTACTPERSONPASSWORD, values);
    }
}
