/**
 * This class is generated by jOOQ
 */
package models.garaDB.tables.records;


import models.garaDB.tables.Carmodel;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "CarModel", schema = "gara")
public class CarmodelRecord extends UpdatableRecordImpl<CarmodelRecord> implements Record6<Integer, String, Integer, Integer, String, Integer> {

    private static final long serialVersionUID = 1082717313;

    /**
     * Setter for <code>gara.CarModel.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gara.CarModel.ID</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID", unique = true, nullable = false, precision = 10)
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gara.CarModel.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gara.CarModel.name</code>.
     */
    @Column(name = "name", nullable = false, length = 65535)
    @NotNull
    @Size(max = 65535)
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gara.CarModel.numberOfSeats</code>.
     */
    public void setNumberofseats(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>gara.CarModel.numberOfSeats</code>.
     */
    @Column(name = "numberOfSeats", precision = 10)
    public Integer getNumberofseats() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>gara.CarModel.carManufactureID</code>.
     */
    public void setCarmanufactureid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>gara.CarModel.carManufactureID</code>.
     */
    @Column(name = "carManufactureID", nullable = false, precision = 10)
    @NotNull
    public Integer getCarmanufactureid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>gara.CarModel.pic</code>.
     */
    public void setPic(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>gara.CarModel.pic</code>.
     */
    @Column(name = "pic", length = 65535)
    @Size(max = 65535)
    public String getPic() {
        return (String) get(4);
    }

    /**
     * Setter for <code>gara.CarModel.gasConsumption</code>.
     */
    public void setGasconsumption(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>gara.CarModel.gasConsumption</code>.
     */
    @Column(name = "gasConsumption", precision = 10)
    public Integer getGasconsumption() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Integer, Integer, String, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Integer, Integer, String, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Carmodel.CARMODEL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Carmodel.CARMODEL.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Carmodel.CARMODEL.NUMBEROFSEATS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Carmodel.CARMODEL.CARMANUFACTUREID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Carmodel.CARMODEL.PIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Carmodel.CARMODEL.GASCONSUMPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getNumberofseats();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCarmanufactureid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPic();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getGasconsumption();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CarmodelRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CarmodelRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CarmodelRecord value3(Integer value) {
        setNumberofseats(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CarmodelRecord value4(Integer value) {
        setCarmanufactureid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CarmodelRecord value5(String value) {
        setPic(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CarmodelRecord value6(Integer value) {
        setGasconsumption(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CarmodelRecord values(Integer value1, String value2, Integer value3, Integer value4, String value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CarmodelRecord
     */
    public CarmodelRecord() {
        super(Carmodel.CARMODEL);
    }

    /**
     * Create a detached, initialised CarmodelRecord
     */
    public CarmodelRecord(Integer id, String name, Integer numberofseats, Integer carmanufactureid, String pic, Integer gasconsumption) {
        super(Carmodel.CARMODEL);

        set(0, id);
        set(1, name);
        set(2, numberofseats);
        set(3, carmanufactureid);
        set(4, pic);
        set(5, gasconsumption);
    }
}
