/**
 * This class is generated by jOOQ
 */
package models.garaDB.tables.records;


import models.garaDB.tables.Membercard;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "MemberCard", schema = "gara")
public class MembercardRecord extends UpdatableRecordImpl<MembercardRecord> implements Record7<Integer, Integer, String, String, String, String, Timestamp> {

    private static final long serialVersionUID = 1035782317;

    /**
     * Setter for <code>gara.MemberCard.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gara.MemberCard.ID</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID", unique = true, nullable = false, precision = 10)
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gara.MemberCard.memberID</code>.
     */
    public void setMemberid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>gara.MemberCard.memberID</code>.
     */
    @Column(name = "memberID", nullable = false, precision = 10)
    @NotNull
    public Integer getMemberid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>gara.MemberCard.type</code>.
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gara.MemberCard.type</code>.
     */
    @Column(name = "type", nullable = false, length = 65535)
    @NotNull
    @Size(max = 65535)
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gara.MemberCard.number</code>.
     */
    public void setNumber(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gara.MemberCard.number</code>.
     */
    @Column(name = "number", nullable = false, length = 65535)
    @NotNull
    @Size(max = 65535)
    public String getNumber() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gara.MemberCard.expireDate</code>.
     */
    public void setExpiredate(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>gara.MemberCard.expireDate</code>.
     */
    @Column(name = "expireDate", nullable = false, length = 65535)
    @NotNull
    @Size(max = 65535)
    public String getExpiredate() {
        return (String) get(4);
    }

    /**
     * Setter for <code>gara.MemberCard.secrit</code>.
     */
    public void setSecrit(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>gara.MemberCard.secrit</code>.
     */
    @Column(name = "secrit", nullable = false, length = 65535)
    @NotNull
    @Size(max = 65535)
    public String getSecrit() {
        return (String) get(5);
    }

    /**
     * Setter for <code>gara.MemberCard.TIMESTAMP</code>.
     */
    public void setTimestamp(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>gara.MemberCard.TIMESTAMP</code>.
     */
    @Column(name = "TIMESTAMP", nullable = false)
    public Timestamp getTimestamp() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, String, String, String, String, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, String, String, String, String, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Membercard.MEMBERCARD.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Membercard.MEMBERCARD.MEMBERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Membercard.MEMBERCARD.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Membercard.MEMBERCARD.NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Membercard.MEMBERCARD.EXPIREDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Membercard.MEMBERCARD.SECRIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Membercard.MEMBERCARD.TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getMemberid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getExpiredate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getSecrit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MembercardRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MembercardRecord value2(Integer value) {
        setMemberid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MembercardRecord value3(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MembercardRecord value4(String value) {
        setNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MembercardRecord value5(String value) {
        setExpiredate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MembercardRecord value6(String value) {
        setSecrit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MembercardRecord value7(Timestamp value) {
        setTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MembercardRecord values(Integer value1, Integer value2, String value3, String value4, String value5, String value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MembercardRecord
     */
    public MembercardRecord() {
        super(Membercard.MEMBERCARD);
    }

    /**
     * Create a detached, initialised MembercardRecord
     */
    public MembercardRecord(Integer id, Integer memberid, String type, String number, String expiredate, String secrit, Timestamp timestamp) {
        super(Membercard.MEMBERCARD);

        set(0, id);
        set(1, memberid);
        set(2, type);
        set(3, number);
        set(4, expiredate);
        set(5, secrit);
        set(6, timestamp);
    }
}
