/**
 * This class is generated by jOOQ
 */
package models.garaDB.tables.records;


import models.garaDB.tables.Membersavedaddress;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "MemberSavedAddress", schema = "gara")
public class MembersavedaddressRecord extends UpdatableRecordImpl<MembersavedaddressRecord> implements Record7<Integer, Integer, String, String, Double, Double, Timestamp> {

    private static final long serialVersionUID = -207451608;

    /**
     * Setter for <code>gara.MemberSavedAddress.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gara.MemberSavedAddress.ID</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID", unique = true, nullable = false, precision = 10)
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gara.MemberSavedAddress.memberID</code>.
     */
    public void setMemberid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>gara.MemberSavedAddress.memberID</code>.
     */
    @Column(name = "memberID", nullable = false, precision = 10)
    @NotNull
    public Integer getMemberid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>gara.MemberSavedAddress.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gara.MemberSavedAddress.name</code>.
     */
    @Column(name = "name", nullable = false, length = 65535)
    @NotNull
    @Size(max = 65535)
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gara.MemberSavedAddress.address</code>.
     */
    public void setAddress(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>gara.MemberSavedAddress.address</code>.
     */
    @Column(name = "address", length = 65535)
    @Size(max = 65535)
    public String getAddress() {
        return (String) get(3);
    }

    /**
     * Setter for <code>gara.MemberSavedAddress.latitude</code>.
     */
    public void setLatitude(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>gara.MemberSavedAddress.latitude</code>.
     */
    @Column(name = "latitude", precision = 22)
    public Double getLatitude() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>gara.MemberSavedAddress.longitude</code>.
     */
    public void setLongitude(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>gara.MemberSavedAddress.longitude</code>.
     */
    @Column(name = "longitude", precision = 22)
    public Double getLongitude() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>gara.MemberSavedAddress.TIMESTAMP</code>.
     */
    public void setTimestamp(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>gara.MemberSavedAddress.TIMESTAMP</code>.
     */
    @Column(name = "TIMESTAMP", nullable = false)
    public Timestamp getTimestamp() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, String, String, Double, Double, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, String, String, Double, Double, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Membersavedaddress.MEMBERSAVEDADDRESS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Membersavedaddress.MEMBERSAVEDADDRESS.MEMBERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Membersavedaddress.MEMBERSAVEDADDRESS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Membersavedaddress.MEMBERSAVEDADDRESS.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return Membersavedaddress.MEMBERSAVEDADDRESS.LATITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return Membersavedaddress.MEMBERSAVEDADDRESS.LONGITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Membersavedaddress.MEMBERSAVEDADDRESS.TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getMemberid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MembersavedaddressRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MembersavedaddressRecord value2(Integer value) {
        setMemberid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MembersavedaddressRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MembersavedaddressRecord value4(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MembersavedaddressRecord value5(Double value) {
        setLatitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MembersavedaddressRecord value6(Double value) {
        setLongitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MembersavedaddressRecord value7(Timestamp value) {
        setTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MembersavedaddressRecord values(Integer value1, Integer value2, String value3, String value4, Double value5, Double value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MembersavedaddressRecord
     */
    public MembersavedaddressRecord() {
        super(Membersavedaddress.MEMBERSAVEDADDRESS);
    }

    /**
     * Create a detached, initialised MembersavedaddressRecord
     */
    public MembersavedaddressRecord(Integer id, Integer memberid, String name, String address, Double latitude, Double longitude, Timestamp timestamp) {
        super(Membersavedaddress.MEMBERSAVEDADDRESS);

        set(0, id);
        set(1, memberid);
        set(2, name);
        set(3, address);
        set(4, latitude);
        set(5, longitude);
        set(6, timestamp);
    }
}
