/**
 * This class is generated by jOOQ
 */
package models.garaDB.tables.records;


import models.garaDB.tables.Membermessage;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "MemberMessage", schema = "gara")
public class MembermessageRecord extends UpdatableRecordImpl<MembermessageRecord> implements Record5<Integer, Timestamp, Integer, Integer, String> {

    private static final long serialVersionUID = -347220786;

    /**
     * Setter for <code>gara.MemberMessage.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>gara.MemberMessage.ID</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID", unique = true, nullable = false, precision = 10)
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>gara.MemberMessage.TIMESTAMP</code>.
     */
    public void setTimestamp(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>gara.MemberMessage.TIMESTAMP</code>.
     */
    @Column(name = "TIMESTAMP", nullable = false)
    public Timestamp getTimestamp() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>gara.MemberMessage.from</code>.
     */
    public void setFrom(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>gara.MemberMessage.from</code>.
     */
    @Column(name = "from", nullable = false, precision = 10)
    @NotNull
    public Integer getFrom() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>gara.MemberMessage.to</code>.
     */
    public void setTo(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>gara.MemberMessage.to</code>.
     */
    @Column(name = "to", nullable = false, precision = 10)
    @NotNull
    public Integer getTo() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>gara.MemberMessage.message</code>.
     */
    public void setMessage(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>gara.MemberMessage.message</code>.
     */
    @Column(name = "message", length = 65535)
    @Size(max = 65535)
    public String getMessage() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Timestamp, Integer, Integer, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Timestamp, Integer, Integer, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Membermessage.MEMBERMESSAGE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Membermessage.MEMBERMESSAGE.TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Membermessage.MEMBERMESSAGE.FROM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Membermessage.MEMBERMESSAGE.TO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Membermessage.MEMBERMESSAGE.MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getFrom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getTo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MembermessageRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MembermessageRecord value2(Timestamp value) {
        setTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MembermessageRecord value3(Integer value) {
        setFrom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MembermessageRecord value4(Integer value) {
        setTo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MembermessageRecord value5(String value) {
        setMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MembermessageRecord values(Integer value1, Timestamp value2, Integer value3, Integer value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MembermessageRecord
     */
    public MembermessageRecord() {
        super(Membermessage.MEMBERMESSAGE);
    }

    /**
     * Create a detached, initialised MembermessageRecord
     */
    public MembermessageRecord(Integer id, Timestamp timestamp, Integer from, Integer to, String message) {
        super(Membermessage.MEMBERMESSAGE);

        set(0, id);
        set(1, timestamp);
        set(2, from);
        set(3, to);
        set(4, message);
    }
}
