/**
 * This class is generated by jOOQ
 */
package models.garaDB.tables.records;


import models.garaDB.tables.Universitypagecontent;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "UniversityPageContent", schema = "Gara")
public class UniversitypagecontentRecord extends UpdatableRecordImpl<UniversitypagecontentRecord> implements Record9<Integer, Timestamp, String, String, String, String, String, String, Integer> {

    private static final long serialVersionUID = 1230586272;

    /**
     * Setter for <code>Gara.UniversityPageContent.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Gara.UniversityPageContent.ID</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID", unique = true, precision = 10)
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Gara.UniversityPageContent.TIMESTAMP</code>.
     */
    public void setTimestamp(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>Gara.UniversityPageContent.TIMESTAMP</code>.
     */
    @Column(name = "TIMESTAMP", nullable = false)
    public Timestamp getTimestamp() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>Gara.UniversityPageContent.title</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>Gara.UniversityPageContent.title</code>.
     */
    @Column(name = "title", length = 65535)
    @Size(max = 65535)
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>Gara.UniversityPageContent.body</code>.
     */
    public void setBody(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>Gara.UniversityPageContent.body</code>.
     */
    @Column(name = "body", length = 65535)
    @Size(max = 65535)
    public String getBody() {
        return (String) get(3);
    }

    /**
     * Setter for <code>Gara.UniversityPageContent.link</code>.
     */
    public void setLink(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>Gara.UniversityPageContent.link</code>.
     */
    @Column(name = "link", length = 65535)
    @Size(max = 65535)
    public String getLink() {
        return (String) get(4);
    }

    /**
     * Setter for <code>Gara.UniversityPageContent.description</code>.
     */
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>Gara.UniversityPageContent.description</code>.
     */
    @Column(name = "description", length = 65535)
    @Size(max = 65535)
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>Gara.UniversityPageContent.keywords</code>.
     */
    public void setKeywords(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>Gara.UniversityPageContent.keywords</code>.
     */
    @Column(name = "keywords", length = 65535)
    @Size(max = 65535)
    public String getKeywords() {
        return (String) get(6);
    }

    /**
     * Setter for <code>Gara.UniversityPageContent.pic</code>.
     */
    public void setPic(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>Gara.UniversityPageContent.pic</code>.
     */
    @Column(name = "pic", length = 65535)
    @Size(max = 65535)
    public String getPic() {
        return (String) get(7);
    }

    /**
     * Setter for <code>Gara.UniversityPageContent.universityID</code>.
     */
    public void setUniversityid(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>Gara.UniversityPageContent.universityID</code>.
     */
    @Column(name = "universityID", nullable = false, precision = 10)
    @NotNull
    public Integer getUniversityid() {
        return (Integer) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Timestamp, String, String, String, String, String, String, Integer> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Timestamp, String, String, String, String, String, String, Integer> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Universitypagecontent.UNIVERSITYPAGECONTENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return Universitypagecontent.UNIVERSITYPAGECONTENT.TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Universitypagecontent.UNIVERSITYPAGECONTENT.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Universitypagecontent.UNIVERSITYPAGECONTENT.BODY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Universitypagecontent.UNIVERSITYPAGECONTENT.LINK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Universitypagecontent.UNIVERSITYPAGECONTENT.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Universitypagecontent.UNIVERSITYPAGECONTENT.KEYWORDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Universitypagecontent.UNIVERSITYPAGECONTENT.PIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Universitypagecontent.UNIVERSITYPAGECONTENT.UNIVERSITYID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getBody();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getLink();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getKeywords();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getPic();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getUniversityid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniversitypagecontentRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniversitypagecontentRecord value2(Timestamp value) {
        setTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniversitypagecontentRecord value3(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniversitypagecontentRecord value4(String value) {
        setBody(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniversitypagecontentRecord value5(String value) {
        setLink(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniversitypagecontentRecord value6(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniversitypagecontentRecord value7(String value) {
        setKeywords(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniversitypagecontentRecord value8(String value) {
        setPic(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniversitypagecontentRecord value9(Integer value) {
        setUniversityid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniversitypagecontentRecord values(Integer value1, Timestamp value2, String value3, String value4, String value5, String value6, String value7, String value8, Integer value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UniversitypagecontentRecord
     */
    public UniversitypagecontentRecord() {
        super(Universitypagecontent.UNIVERSITYPAGECONTENT);
    }

    /**
     * Create a detached, initialised UniversitypagecontentRecord
     */
    public UniversitypagecontentRecord(Integer id, Timestamp timestamp, String title, String body, String link, String description, String keywords, String pic, Integer universityid) {
        super(Universitypagecontent.UNIVERSITYPAGECONTENT);

        set(0, id);
        set(1, timestamp);
        set(2, title);
        set(3, body);
        set(4, link);
        set(5, description);
        set(6, keywords);
        set(7, pic);
        set(8, universityid);
    }
}
