/**
 * This class is generated by jOOQ
 */
package models.garaDB.tables;


import models.garaDB.Gara;
import models.garaDB.Keys;
import models.garaDB.tables.records.CarmodelRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Carmodel extends TableImpl<CarmodelRecord> {

    private static final long serialVersionUID = -763663733;

    /**
     * The reference instance of <code>Gara.CarModel</code>
     */
    public static final Carmodel CARMODEL = new Carmodel();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CarmodelRecord> getRecordType() {
        return CarmodelRecord.class;
    }

    /**
     * The column <code>Gara.CarModel.ID</code>.
     */
    public final TableField<CarmodelRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>Gara.CarModel.name</code>.
     */
    public final TableField<CarmodelRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>Gara.CarModel.numberOfSeats</code>.
     */
    public final TableField<CarmodelRecord, Integer> NUMBEROFSEATS = createField("numberOfSeats", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>Gara.CarModel.carManufactureID</code>.
     */
    public final TableField<CarmodelRecord, Integer> CARMANUFACTUREID = createField("carManufactureID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>Gara.CarModel.pic</code>.
     */
    public final TableField<CarmodelRecord, String> PIC = createField("pic", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>Gara.CarModel</code> table reference
     */
    public Carmodel() {
        this("CarModel", null);
    }

    /**
     * Create an aliased <code>Gara.CarModel</code> table reference
     */
    public Carmodel(String alias) {
        this(alias, CARMODEL);
    }

    private Carmodel(String alias, Table<CarmodelRecord> aliased) {
        this(alias, aliased, null);
    }

    private Carmodel(String alias, Table<CarmodelRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Gara.GARA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CarmodelRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CARMODEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CarmodelRecord> getPrimaryKey() {
        return Keys.KEY_CARMODEL_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CarmodelRecord>> getKeys() {
        return Arrays.<UniqueKey<CarmodelRecord>>asList(Keys.KEY_CARMODEL_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CarmodelRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CarmodelRecord, ?>>asList(Keys.FKCARMODEL191241);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Carmodel as(String alias) {
        return new Carmodel(alias, this);
    }

    /**
     * Rename this table
     */
    public Carmodel rename(String name) {
        return new Carmodel(name, null);
    }
}
