/**
 * This class is generated by jOOQ
 */
package models.garaDB.tables;


import models.garaDB.Gara;
import models.garaDB.Keys;
import models.garaDB.tables.records.CarmanufactureRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Carmanufacture extends TableImpl<CarmanufactureRecord> {

    private static final long serialVersionUID = 687794818;

    /**
     * The reference instance of <code>Gara.CarManufacture</code>
     */
    public static final Carmanufacture CARMANUFACTURE = new Carmanufacture();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CarmanufactureRecord> getRecordType() {
        return CarmanufactureRecord.class;
    }

    /**
     * The column <code>Gara.CarManufacture.ID</code>.
     */
    public final TableField<CarmanufactureRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>Gara.CarManufacture.name</code>.
     */
    public final TableField<CarmanufactureRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>Gara.CarManufacture.countryID</code>.
     */
    public final TableField<CarmanufactureRecord, Integer> COUNTRYID = createField("countryID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>Gara.CarManufacture.pic</code>.
     */
    public final TableField<CarmanufactureRecord, String> PIC = createField("pic", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>Gara.CarManufacture</code> table reference
     */
    public Carmanufacture() {
        this("CarManufacture", null);
    }

    /**
     * Create an aliased <code>Gara.CarManufacture</code> table reference
     */
    public Carmanufacture(String alias) {
        this(alias, CARMANUFACTURE);
    }

    private Carmanufacture(String alias, Table<CarmanufactureRecord> aliased) {
        this(alias, aliased, null);
    }

    private Carmanufacture(String alias, Table<CarmanufactureRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Gara.GARA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CarmanufactureRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CARMANUFACTURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CarmanufactureRecord> getPrimaryKey() {
        return Keys.KEY_CARMANUFACTURE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CarmanufactureRecord>> getKeys() {
        return Arrays.<UniqueKey<CarmanufactureRecord>>asList(Keys.KEY_CARMANUFACTURE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CarmanufactureRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CarmanufactureRecord, ?>>asList(Keys.FKCARMANUFAC421407);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Carmanufacture as(String alias) {
        return new Carmanufacture(alias, this);
    }

    /**
     * Rename this table
     */
    public Carmanufacture rename(String name) {
        return new Carmanufacture(name, null);
    }
}
