/**
 * This class is generated by jOOQ
 */
package models.garaDB.tables;


import models.garaDB.Gara;
import models.garaDB.Keys;
import models.garaDB.tables.records.MembergroupRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Membergroup extends TableImpl<MembergroupRecord> {

    private static final long serialVersionUID = 1402440506;

    /**
     * The reference instance of <code>Gara.MemberGroup</code>
     */
    public static final Membergroup MEMBERGROUP = new Membergroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MembergroupRecord> getRecordType() {
        return MembergroupRecord.class;
    }

    /**
     * The column <code>Gara.MemberGroup.ID</code>.
     */
    public final TableField<MembergroupRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>Gara.MemberGroup.name</code>.
     */
    public final TableField<MembergroupRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>Gara.MemberGroup.description</code>.
     */
    public final TableField<MembergroupRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>Gara.MemberGroup.permissions</code>.
     */
    public final TableField<MembergroupRecord, String> PERMISSIONS = createField("permissions", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>Gara.MemberGroup</code> table reference
     */
    public Membergroup() {
        this("MemberGroup", null);
    }

    /**
     * Create an aliased <code>Gara.MemberGroup</code> table reference
     */
    public Membergroup(String alias) {
        this(alias, MEMBERGROUP);
    }

    private Membergroup(String alias, Table<MembergroupRecord> aliased) {
        this(alias, aliased, null);
    }

    private Membergroup(String alias, Table<MembergroupRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Gara.GARA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<MembergroupRecord, Integer> getIdentity() {
        return Keys.IDENTITY_MEMBERGROUP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MembergroupRecord> getPrimaryKey() {
        return Keys.KEY_MEMBERGROUP_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MembergroupRecord>> getKeys() {
        return Arrays.<UniqueKey<MembergroupRecord>>asList(Keys.KEY_MEMBERGROUP_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Membergroup as(String alias) {
        return new Membergroup(alias, this);
    }

    /**
     * Rename this table
     */
    public Membergroup rename(String name) {
        return new Membergroup(name, null);
    }
}
