/**
 * This class is generated by jOOQ
 */
package models.garaDB.tables;


import models.garaDB.Gara;
import models.garaDB.Keys;
import models.garaDB.tables.records.MembersavedaddressRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Membersavedaddress extends TableImpl<MembersavedaddressRecord> {

    private static final long serialVersionUID = -1905803231;

    /**
     * The reference instance of <code>gara.MemberSavedAddress</code>
     */
    public static final Membersavedaddress MEMBERSAVEDADDRESS = new Membersavedaddress();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MembersavedaddressRecord> getRecordType() {
        return MembersavedaddressRecord.class;
    }

    /**
     * The column <code>gara.MemberSavedAddress.ID</code>.
     */
    public final TableField<MembersavedaddressRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>gara.MemberSavedAddress.memberID</code>.
     */
    public final TableField<MembersavedaddressRecord, Integer> MEMBERID = createField("memberID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>gara.MemberSavedAddress.name</code>.
     */
    public final TableField<MembersavedaddressRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>gara.MemberSavedAddress.address</code>.
     */
    public final TableField<MembersavedaddressRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>gara.MemberSavedAddress.latitude</code>.
     */
    public final TableField<MembersavedaddressRecord, Double> LATITUDE = createField("latitude", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>gara.MemberSavedAddress.longitude</code>.
     */
    public final TableField<MembersavedaddressRecord, Double> LONGITUDE = createField("longitude", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>gara.MemberSavedAddress.TIMESTAMP</code>.
     */
    public final TableField<MembersavedaddressRecord, Timestamp> TIMESTAMP = createField("TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>gara.MemberSavedAddress</code> table reference
     */
    public Membersavedaddress() {
        this("MemberSavedAddress", null);
    }

    /**
     * Create an aliased <code>gara.MemberSavedAddress</code> table reference
     */
    public Membersavedaddress(String alias) {
        this(alias, MEMBERSAVEDADDRESS);
    }

    private Membersavedaddress(String alias, Table<MembersavedaddressRecord> aliased) {
        this(alias, aliased, null);
    }

    private Membersavedaddress(String alias, Table<MembersavedaddressRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Gara.GARA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<MembersavedaddressRecord, Integer> getIdentity() {
        return Keys.IDENTITY_MEMBERSAVEDADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<MembersavedaddressRecord> getPrimaryKey() {
        return Keys.KEY_MEMBERSAVEDADDRESS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<MembersavedaddressRecord>> getKeys() {
        return Arrays.<UniqueKey<MembersavedaddressRecord>>asList(Keys.KEY_MEMBERSAVEDADDRESS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<MembersavedaddressRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<MembersavedaddressRecord, ?>>asList(Keys.FKMEMBERSAVE41459);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Membersavedaddress as(String alias) {
        return new Membersavedaddress(alias, this);
    }

    /**
     * Rename this table
     */
    public Membersavedaddress rename(String name) {
        return new Membersavedaddress(name, null);
    }
}
