/**
 * This class is generated by jOOQ
 */
package models.garaDB.tables;


import models.garaDB.Gara;
import models.garaDB.Keys;
import models.garaDB.tables.records.SitecontentRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sitecontent extends TableImpl<SitecontentRecord> {

    private static final long serialVersionUID = 1922502976;

    /**
     * The reference instance of <code>Gara.SiteContent</code>
     */
    public static final Sitecontent SITECONTENT = new Sitecontent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SitecontentRecord> getRecordType() {
        return SitecontentRecord.class;
    }

    /**
     * The column <code>Gara.SiteContent.ID</code>.
     */
    public final TableField<SitecontentRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>Gara.SiteContent.TIMESTAMP</code>.
     */
    public final TableField<SitecontentRecord, Timestamp> TIMESTAMP = createField("TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>Gara.SiteContent.title</code>.
     */
    public final TableField<SitecontentRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>Gara.SiteContent.body</code>.
     */
    public final TableField<SitecontentRecord, String> BODY = createField("body", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>Gara.SiteContent.link</code>.
     */
    public final TableField<SitecontentRecord, String> LINK = createField("link", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>Gara.SiteContent.description</code>.
     */
    public final TableField<SitecontentRecord, String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>Gara.SiteContent.keywords</code>.
     */
    public final TableField<SitecontentRecord, String> KEYWORDS = createField("keywords", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>Gara.SiteContent.pic</code>.
     */
    public final TableField<SitecontentRecord, String> PIC = createField("pic", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>Gara.SiteContent.name</code>.
     */
    public final TableField<SitecontentRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>Gara.SiteContent</code> table reference
     */
    public Sitecontent() {
        this("SiteContent", null);
    }

    /**
     * Create an aliased <code>Gara.SiteContent</code> table reference
     */
    public Sitecontent(String alias) {
        this(alias, SITECONTENT);
    }

    private Sitecontent(String alias, Table<SitecontentRecord> aliased) {
        this(alias, aliased, null);
    }

    private Sitecontent(String alias, Table<SitecontentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Gara.GARA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SitecontentRecord, Integer> getIdentity() {
        return Keys.IDENTITY_SITECONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SitecontentRecord> getPrimaryKey() {
        return Keys.KEY_SITECONTENT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SitecontentRecord>> getKeys() {
        return Arrays.<UniqueKey<SitecontentRecord>>asList(Keys.KEY_SITECONTENT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Sitecontent as(String alias) {
        return new Sitecontent(alias, this);
    }

    /**
     * Rename this table
     */
    public Sitecontent rename(String name) {
        return new Sitecontent(name, null);
    }
}
