/**
 * This class is generated by jOOQ
 */
package models.garaDB;


import models.garaDB.tables.Accesstoken;
import models.garaDB.tables.Car;
import models.garaDB.tables.Carmanufacture;
import models.garaDB.tables.Carmodel;
import models.garaDB.tables.City;
import models.garaDB.tables.College;
import models.garaDB.tables.Country;
import models.garaDB.tables.Databasechangelog;
import models.garaDB.tables.Databasechangeloglock;
import models.garaDB.tables.Driver;
import models.garaDB.tables.Member;
import models.garaDB.tables.Membercard;
import models.garaDB.tables.Membergroup;
import models.garaDB.tables.Membermessage;
import models.garaDB.tables.Membersavedaddress;
import models.garaDB.tables.Review;
import models.garaDB.tables.Ride;
import models.garaDB.tables.Sitecontent;
import models.garaDB.tables.Sitecontentgroup;
import models.garaDB.tables.Siteoption;
import models.garaDB.tables.University;
import models.garaDB.tables.Universitypagecontent;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Gara extends SchemaImpl {

    private static final long serialVersionUID = -1012714021;

    /**
     * The reference instance of <code>Gara</code>
     */
    public static final Gara GARA = new Gara();

    /**
     * The table <code>Gara.AccessToken</code>.
     */
    public final Accesstoken ACCESSTOKEN = models.garaDB.tables.Accesstoken.ACCESSTOKEN;

    /**
     * The table <code>Gara.Car</code>.
     */
    public final Car CAR = models.garaDB.tables.Car.CAR;

    /**
     * The table <code>Gara.CarManufacture</code>.
     */
    public final Carmanufacture CARMANUFACTURE = models.garaDB.tables.Carmanufacture.CARMANUFACTURE;

    /**
     * The table <code>Gara.CarModel</code>.
     */
    public final Carmodel CARMODEL = models.garaDB.tables.Carmodel.CARMODEL;

    /**
     * The table <code>Gara.City</code>.
     */
    public final City CITY = models.garaDB.tables.City.CITY;

    /**
     * The table <code>Gara.College</code>.
     */
    public final College COLLEGE = models.garaDB.tables.College.COLLEGE;

    /**
     * The table <code>Gara.Country</code>.
     */
    public final Country COUNTRY = models.garaDB.tables.Country.COUNTRY;

    /**
     * The table <code>Gara.DATABASECHANGELOG</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = models.garaDB.tables.Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>Gara.DATABASECHANGELOGLOCK</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = models.garaDB.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>Gara.Driver</code>.
     */
    public final Driver DRIVER = models.garaDB.tables.Driver.DRIVER;

    /**
     * The table <code>Gara.Member</code>.
     */
    public final Member MEMBER = models.garaDB.tables.Member.MEMBER;

    /**
     * The table <code>Gara.MemberCard</code>.
     */
    public final Membercard MEMBERCARD = models.garaDB.tables.Membercard.MEMBERCARD;

    /**
     * The table <code>Gara.MemberGroup</code>.
     */
    public final Membergroup MEMBERGROUP = models.garaDB.tables.Membergroup.MEMBERGROUP;

    /**
     * The table <code>Gara.MemberMessage</code>.
     */
    public final Membermessage MEMBERMESSAGE = models.garaDB.tables.Membermessage.MEMBERMESSAGE;

    /**
     * The table <code>Gara.MemberSavedAddress</code>.
     */
    public final Membersavedaddress MEMBERSAVEDADDRESS = models.garaDB.tables.Membersavedaddress.MEMBERSAVEDADDRESS;

    /**
     * The table <code>Gara.Review</code>.
     */
    public final Review REVIEW = models.garaDB.tables.Review.REVIEW;

    /**
     * The table <code>Gara.Ride</code>.
     */
    public final Ride RIDE = models.garaDB.tables.Ride.RIDE;

    /**
     * The table <code>Gara.SiteContent</code>.
     */
    public final Sitecontent SITECONTENT = models.garaDB.tables.Sitecontent.SITECONTENT;

    /**
     * The table <code>Gara.SiteContentGroup</code>.
     */
    public final Sitecontentgroup SITECONTENTGROUP = models.garaDB.tables.Sitecontentgroup.SITECONTENTGROUP;

    /**
     * The table <code>Gara.SiteOption</code>.
     */
    public final Siteoption SITEOPTION = models.garaDB.tables.Siteoption.SITEOPTION;

    /**
     * The table <code>Gara.University</code>.
     */
    public final University UNIVERSITY = models.garaDB.tables.University.UNIVERSITY;

    /**
     * The table <code>Gara.UniversityPageContent</code>.
     */
    public final Universitypagecontent UNIVERSITYPAGECONTENT = models.garaDB.tables.Universitypagecontent.UNIVERSITYPAGECONTENT;

    /**
     * No further instances allowed
     */
    private Gara() {
        super("Gara", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Accesstoken.ACCESSTOKEN,
            Car.CAR,
            Carmanufacture.CARMANUFACTURE,
            Carmodel.CARMODEL,
            City.CITY,
            College.COLLEGE,
            Country.COUNTRY,
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            Driver.DRIVER,
            Member.MEMBER,
            Membercard.MEMBERCARD,
            Membergroup.MEMBERGROUP,
            Membermessage.MEMBERMESSAGE,
            Membersavedaddress.MEMBERSAVEDADDRESS,
            Review.REVIEW,
            Ride.RIDE,
            Sitecontent.SITECONTENT,
            Sitecontentgroup.SITECONTENTGROUP,
            Siteoption.SITEOPTION,
            University.UNIVERSITY,
            Universitypagecontent.UNIVERSITYPAGECONTENT);
    }
}
