/**
 * This class is generated by jOOQ
 */
package models.garaDB.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "Car", schema = "Gara")
public class Car implements Serializable {

    private static final long serialVersionUID = 935799066;

    private Integer id;
    private Integer driverid;
    private String  platenumber;
    private String  platepic;
    private Integer carmodelid;
    private String  frontpic;
    private String  backpic;
    private String  sidepic;
    private String  insidepic;
    private String  licensenumber;
    private String  licensepic;
    private Date    licenseexpiredate;
    private Double  distlongitude;
    private Double  distlatitude;
    private Integer availableseats;
    private Boolean state;

    public Car() {}

    public Car(Car value) {
        this.id = value.id;
        this.driverid = value.driverid;
        this.platenumber = value.platenumber;
        this.platepic = value.platepic;
        this.carmodelid = value.carmodelid;
        this.frontpic = value.frontpic;
        this.backpic = value.backpic;
        this.sidepic = value.sidepic;
        this.insidepic = value.insidepic;
        this.licensenumber = value.licensenumber;
        this.licensepic = value.licensepic;
        this.licenseexpiredate = value.licenseexpiredate;
        this.distlongitude = value.distlongitude;
        this.distlatitude = value.distlatitude;
        this.availableseats = value.availableseats;
        this.state = value.state;
    }

    public Car(
        Integer id,
        Integer driverid,
        String  platenumber,
        String  platepic,
        Integer carmodelid,
        String  frontpic,
        String  backpic,
        String  sidepic,
        String  insidepic,
        String  licensenumber,
        String  licensepic,
        Date    licenseexpiredate,
        Double  distlongitude,
        Double  distlatitude,
        Integer availableseats,
        Boolean state
    ) {
        this.id = id;
        this.driverid = driverid;
        this.platenumber = platenumber;
        this.platepic = platepic;
        this.carmodelid = carmodelid;
        this.frontpic = frontpic;
        this.backpic = backpic;
        this.sidepic = sidepic;
        this.insidepic = insidepic;
        this.licensenumber = licensenumber;
        this.licensepic = licensepic;
        this.licenseexpiredate = licenseexpiredate;
        this.distlongitude = distlongitude;
        this.distlatitude = distlatitude;
        this.availableseats = availableseats;
        this.state = state;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID", unique = true, nullable = false, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "driverID", nullable = false, precision = 10)
    @NotNull
    public Integer getDriverid() {
        return this.driverid;
    }

    public void setDriverid(Integer driverid) {
        this.driverid = driverid;
    }

    @Column(name = "plateNumber", nullable = false, length = 65535)
    @NotNull
    @Size(max = 65535)
    public String getPlatenumber() {
        return this.platenumber;
    }

    public void setPlatenumber(String platenumber) {
        this.platenumber = platenumber;
    }

    @Column(name = "platePic", length = 65535)
    @Size(max = 65535)
    public String getPlatepic() {
        return this.platepic;
    }

    public void setPlatepic(String platepic) {
        this.platepic = platepic;
    }

    @Column(name = "carModelID", nullable = false, precision = 10)
    @NotNull
    public Integer getCarmodelid() {
        return this.carmodelid;
    }

    public void setCarmodelid(Integer carmodelid) {
        this.carmodelid = carmodelid;
    }

    @Column(name = "frontPic", length = 65535)
    @Size(max = 65535)
    public String getFrontpic() {
        return this.frontpic;
    }

    public void setFrontpic(String frontpic) {
        this.frontpic = frontpic;
    }

    @Column(name = "backPic", length = 65535)
    @Size(max = 65535)
    public String getBackpic() {
        return this.backpic;
    }

    public void setBackpic(String backpic) {
        this.backpic = backpic;
    }

    @Column(name = "sidePic", length = 65535)
    @Size(max = 65535)
    public String getSidepic() {
        return this.sidepic;
    }

    public void setSidepic(String sidepic) {
        this.sidepic = sidepic;
    }

    @Column(name = "insidePic", length = 65535)
    @Size(max = 65535)
    public String getInsidepic() {
        return this.insidepic;
    }

    public void setInsidepic(String insidepic) {
        this.insidepic = insidepic;
    }

    @Column(name = "licenseNumber", nullable = false, length = 65535)
    @NotNull
    @Size(max = 65535)
    public String getLicensenumber() {
        return this.licensenumber;
    }

    public void setLicensenumber(String licensenumber) {
        this.licensenumber = licensenumber;
    }

    @Column(name = "licensePic", length = 65535)
    @Size(max = 65535)
    public String getLicensepic() {
        return this.licensepic;
    }

    public void setLicensepic(String licensepic) {
        this.licensepic = licensepic;
    }

    @Column(name = "licenseExpireDate", nullable = false)
    @NotNull
    public Date getLicenseexpiredate() {
        return this.licenseexpiredate;
    }

    public void setLicenseexpiredate(Date licenseexpiredate) {
        this.licenseexpiredate = licenseexpiredate;
    }

    @Column(name = "DistLongitude", precision = 22)
    public Double getDistlongitude() {
        return this.distlongitude;
    }

    public void setDistlongitude(Double distlongitude) {
        this.distlongitude = distlongitude;
    }

    @Column(name = "DistLatitude", precision = 22)
    public Double getDistlatitude() {
        return this.distlatitude;
    }

    public void setDistlatitude(Double distlatitude) {
        this.distlatitude = distlatitude;
    }

    @Column(name = "availableSeats", precision = 10)
    public Integer getAvailableseats() {
        return this.availableseats;
    }

    public void setAvailableseats(Integer availableseats) {
        this.availableseats = availableseats;
    }

    @Column(name = "state", precision = 1)
    public Boolean getState() {
        return this.state;
    }

    public void setState(Boolean state) {
        this.state = state;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Car (");

        sb.append(id);
        sb.append(", ").append(driverid);
        sb.append(", ").append(platenumber);
        sb.append(", ").append(platepic);
        sb.append(", ").append(carmodelid);
        sb.append(", ").append(frontpic);
        sb.append(", ").append(backpic);
        sb.append(", ").append(sidepic);
        sb.append(", ").append(insidepic);
        sb.append(", ").append(licensenumber);
        sb.append(", ").append(licensepic);
        sb.append(", ").append(licenseexpiredate);
        sb.append(", ").append(distlongitude);
        sb.append(", ").append(distlatitude);
        sb.append(", ").append(availableseats);
        sb.append(", ").append(state);

        sb.append(")");
        return sb.toString();
    }
}
