/**
 * This class is generated by jOOQ
 */
package models.garaDB.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "College", schema = "Gara")
public class College implements Serializable {

    private static final long serialVersionUID = -711446977;

    private Integer id;
    private Integer universityid;
    private String  name;

    public College() {}

    public College(College value) {
        this.id = value.id;
        this.universityid = value.universityid;
        this.name = value.name;
    }

    public College(
        Integer id,
        Integer universityid,
        String  name
    ) {
        this.id = id;
        this.universityid = universityid;
        this.name = name;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID", unique = true, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "universityID", nullable = false, precision = 10)
    @NotNull
    public Integer getUniversityid() {
        return this.universityid;
    }

    public void setUniversityid(Integer universityid) {
        this.universityid = universityid;
    }

    @Column(name = "name", nullable = false, length = 65535)
    @NotNull
    @Size(max = 65535)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("College (");

        sb.append(id);
        sb.append(", ").append(universityid);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
