/**
 * This class is generated by jOOQ
 */
package models.garaDB.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "MemberMessage", schema = "Gara")
public class Membermessage implements Serializable {

    private static final long serialVersionUID = 1325922620;

    private Integer   id;
    private Timestamp timestamp;
    private Integer   from;
    private Integer   to;
    private String    message;

    public Membermessage() {}

    public Membermessage(Membermessage value) {
        this.id = value.id;
        this.timestamp = value.timestamp;
        this.from = value.from;
        this.to = value.to;
        this.message = value.message;
    }

    public Membermessage(
        Integer   id,
        Timestamp timestamp,
        Integer   from,
        Integer   to,
        String    message
    ) {
        this.id = id;
        this.timestamp = timestamp;
        this.from = from;
        this.to = to;
        this.message = message;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID", unique = true, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "TIMESTAMP", nullable = false)
    public Timestamp getTimestamp() {
        return this.timestamp;
    }

    public void setTimestamp(Timestamp timestamp) {
        this.timestamp = timestamp;
    }

    @Column(name = "from", nullable = false, precision = 10)
    @NotNull
    public Integer getFrom() {
        return this.from;
    }

    public void setFrom(Integer from) {
        this.from = from;
    }

    @Column(name = "to", nullable = false, precision = 10)
    @NotNull
    public Integer getTo() {
        return this.to;
    }

    public void setTo(Integer to) {
        this.to = to;
    }

    @Column(name = "message", length = 65535)
    @Size(max = 65535)
    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Membermessage (");

        sb.append(id);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(from);
        sb.append(", ").append(to);
        sb.append(", ").append(message);

        sb.append(")");
        return sb.toString();
    }
}
