/**
 * This class is generated by jOOQ
 */
package models.garaDB.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "Review", schema = "Gara")
public class Review implements Serializable {

    private static final long serialVersionUID = -682694105;

    private Integer id;
    private Integer reviewermemberid;
    private Integer reviewedmemberid;
    private Integer rating;
    private String  comment;

    public Review() {}

    public Review(Review value) {
        this.id = value.id;
        this.reviewermemberid = value.reviewermemberid;
        this.reviewedmemberid = value.reviewedmemberid;
        this.rating = value.rating;
        this.comment = value.comment;
    }

    public Review(
        Integer id,
        Integer reviewermemberid,
        Integer reviewedmemberid,
        Integer rating,
        String  comment
    ) {
        this.id = id;
        this.reviewermemberid = reviewermemberid;
        this.reviewedmemberid = reviewedmemberid;
        this.rating = rating;
        this.comment = comment;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID", unique = true, nullable = false, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "reviewerMemberID", nullable = false, precision = 10)
    @NotNull
    public Integer getReviewermemberid() {
        return this.reviewermemberid;
    }

    public void setReviewermemberid(Integer reviewermemberid) {
        this.reviewermemberid = reviewermemberid;
    }

    @Column(name = "reviewedMemberID", nullable = false, precision = 10)
    @NotNull
    public Integer getReviewedmemberid() {
        return this.reviewedmemberid;
    }

    public void setReviewedmemberid(Integer reviewedmemberid) {
        this.reviewedmemberid = reviewedmemberid;
    }

    @Column(name = "rating", nullable = false, precision = 10)
    @NotNull
    public Integer getRating() {
        return this.rating;
    }

    public void setRating(Integer rating) {
        this.rating = rating;
    }

    @Column(name = "comment", length = 65535)
    @Size(max = 65535)
    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Review (");

        sb.append(id);
        sb.append(", ").append(reviewermemberid);
        sb.append(", ").append(reviewedmemberid);
        sb.append(", ").append(rating);
        sb.append(", ").append(comment);

        sb.append(")");
        return sb.toString();
    }
}
